COLUMNS:
  carat : float64
  cut : str
  color : str
  clarity : str
  depth : float64
  table : float64
  x : float64
  y : float64
  z : float64

TARGET_COLUMN:
 name: price




















TARGET_COLUMN: